modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="allthearmor"
version="v2.1.0"
displayName="All The Armor"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="beeze, MCreator"
description='''
A Mod That Adds A TON Of Armor
'''

[[dependencies.allthearmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




